Feat/jl 361 internal link
webbio/strapi-plugin-internal-links pull request #37
Opened 2024-05-21 08:21 UTC by MikeVanEssen

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio requested changes
Ook even de README updaten met de nieuwe types.

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/api/page/content-types/page/schema.json
> +				"externalApi": "",
is er een reden dat je al die opties toevoegt?

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/api/fetch-source.ts
> +				url: externalApiUrl,
deze mogen undefined zijn, wat gebeurt er als die allemaal leeg is?

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/index.tsx
> +		} else if (isSourceTab) {
else if is niet nodig bij een return.

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/index.tsx
> +				label="Some stuff for the label"
deze waarde invullen?

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/index.tsx
> +					<Tab>Internal</Tab>
vertalingen gebruiken?

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/index.tsx
> +					{/* This is the first tab */}
is het een idee om alle tabjes in aparte bestanden te zetten? Nu is dit bestand nog mega'er dan 'ie al was.

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/input/index.tsx
> +		enableExternalApi?: boolean;
ik denk dat het overzichtelijker is om hier een object van te maken. Dus:
```
externalApi?: {
	enabled?: boolean;
	labelPath?: string;
	valuePath?: string;
	apiUrl?: string;
}
```

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/package.json
> +		"axios": "^1.6.8",
waarom axios en niet gewoon fetch?

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/server/services/external-source.ts
> +	return res;
hier kan je toch gewoon fetch gebruiken?

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/server/services/external-source.ts
> +	const url = createUrl(data);
in de admin wordt de url als optioneel beschouwd. Dus hier ook ff een check doen of die bestaat.

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/api/fetch-source.ts
> +	data: any[];
Record<string,any>

2024-05-21 08:35 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/source-select/index.tsx
> +			value: item[externalApiValueMapping],
ik zou hier de get van lodash gebruiken zodat je ook een heel pad mee kan geven. Dus get(item, path)

2024-05-21 12:09 UTC, TomWebbio requested changes

2024-05-21 12:09 UTC, TomWebbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/source-select/index.tsx
> +
enter mag weg :p

2024-05-21 12:09 UTC, TomWebbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/source-select/index.tsx
> +	const debouncedFetch = debounce((searchTerm, callback) => {
Ik zou dit liever een duidelijke naam willen hebben, je hoeft in de naam niet te zetten dat iets een debounce is. Meer iets wat lijkt op getAllOptions ofzo

2024-05-21 12:09 UTC, TomWebbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/source-select/index.tsx
> +					loadOptions={(i, c) => debouncedFetch(i, c)}
ben niet zon fan van enkel letterige variabelen

2024-05-22 07:40 UTC, TomWebbio approved these changes

2024-05-22 08:33 UTC, merged

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio reviewed
Per tab worden er ook nog isExternal checks gedaan. Dat is niet meer nodig aangezien je weet welke tab het is.

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/README.md
> +"options": {
hoezo voeg je deze opties niet toe aan de bestaande opties bovenin?

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/index.tsx
> +			return 0;
else hoeft niet bij een return

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/source-select/index.tsx
> +		const externalItems = await fetchSource({ fetchClient }, externalApiUrl, inputValue);
hier wordt niet de check gedaan of die externalApiUrl bestaat

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/source-select/index.tsx
> +					key={`externalApiSearch`}
key is enkel nodig voor het rerenderen wat we bij andere comboboxen moesten doen.

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/api/fetch-source.ts
> +		const { post } = fetchClient;
ik zou voor de zekerheid hier dus de check doen of die externalApiUrl bestaat

2024-05-22 08:58 UTC, Martijn-Schoenmaker-Webbio commented on src/plugins/strapi-plugin-internal-links/admin/src/components/form/index.tsx
> +	const [isSourceTab, setIsSourceTab] = useState<boolean>(link.type === 'source');
Dit zou beter 1 state kunnen zijn die "external" | "source" |"internal" kan zijn.